function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 24-Feb-2016 11:20:52

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YScale','log','YMinorTick','on',...
    'YMinorGrid','on',...
    'XScale','log',...
    'XMinorTick','on',...
    'XMinorGrid','on',...
    'FontSize',12,...
    'FontName','Garamond');
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to loglog
loglog1 = loglog(X1,YMatrix1,'Parent',axes1);
set(loglog1(1),'LineWidth',4,'LineStyle','--','DisplayName','DC = 0.2',...
    'Color',[0 0 0]);
set(loglog1(2),'MarkerSize',20,'Marker','.','LineWidth',2,'Color',[1 0 0],...
    'DisplayName','DC = 0.09');
set(loglog1(3),'MarkerSize',8,'Marker','o','LineWidth',2,'Color',[0 0 1],...
    'DisplayName','DC = 0.025');
set(loglog1(4),'MarkerSize',10,'Marker','*','LineWidth',2,'Color',[0 1 0],...
    'DisplayName','DC = 0.01');
set(loglog1(5),'LineWidth',2,'LineStyle','--','Color',[0 0 0]);
set(loglog1(6),'MarkerSize',20,'Marker','.','LineWidth',1.5,'Color',[1 0 0]);
set(loglog1(7),'MarkerSize',8,'Marker','o','LineWidth',1.5,'Color',[0 0 1]);
set(loglog1(8),'MarkerSize',10,'Marker','*','LineWidth',1.5,'Color',[0 1 0]);

% Create xlabel
xlabel('V_{TBP}/V_{HNO_{3}}','FontSize',12,'FontName','Garamond');

% Create ylabel
ylabel('Decontamination Factor of solute in TBP','FontSize',12,...
    'FontName','Garamond');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.176488095238095 0.232142857142857 0.241071428571428 0.207936507936508]);

